# app
spring:
  application.name: konce
  config.import: optional:file:.env[.properties]
# db
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
## jpa
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 28800
  refresh-token-expiration: 288000